/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package c.ejercicio_03_06;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author admin
 */
public class Dibujo extends javax.swing.JPanel {

    /**
     * Creates new form Dibujo
     */
    
    Grafico G;
    public Dibujo() {
        initComponents();
        G = new Grafico();
        
    }
    
    public void enviarCoordenadas(int x, int y){
        G.setX(x);
        G.setY(y);
    }
    
    public void enviarAnchoAlto(int ancho, int alto){
        G.setAncho(ancho);
        G.setAlto(alto);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        
        //G.dibujarCirculo(g);
        //G.dibujarRectangulo(g);
        //G.dibujarCuadrado(g);
        G.dibujarEstrella(g);
        //G.dibujarTriangulo(g);
    }
    
    public void Actualizar(){
        repaint();
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
